services:
  - type: web
    name: lotto-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: lotto-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: lotto-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: lotto-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: lotto-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: lotto-db
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: BCRYPT_ROUNDS
        value: 12
      - key: CORS_ORIGIN
        value: "*"

databases:
  - name: lotto-db
    databaseName: lotto_database
    user: lotto_user
    plan: free